[window]
padding = {x = 0, y = 0}
decorations = "Full"
opacity = 0.75
blur = true
dynamic_title = false

[scrolling]
history = 100000

[font]
size=12

[colors.primary]
background = '#000000'

[selection]
save_to_clipboard=true

[cursor]
style={shape="Block", blinking="Always"}
blink_interval=250
blink_timeout=0
unfocused_hollow=true

[mouse]
hide_when_typing=true
